### PR TITLE
Fixed reture value of the 'upstream-idle' cli script.

### PR DESCRIPTION
**Pull request by torsava**

### CODE REVIEW

**Comment by encukou** [comment]
The doc says `Exits with error code 1 if such packages are found.`. That's on purpose – it's “bad” if such packages exist.

**Comment by torsava** [comment]
Oh, I thought you said it's so you can use it in pipes and so on, which the current implementation prevents I believe.

**Comment by encukou** [comment]
It shouldn't. What's the pipeline you're having trouble with?

**Comment by torsava** [comment]
Never mind, I just had enabled zsh/bash option `pipefail`. Sorry!

**Pull request closed without merging**
