### PR TITLE
Two little dev usability fixes

### PR DESCRIPTION
**Pull request by encukou**
See commit messages

### CODE REVIEW

**Comment by hroncok** [comment]
Why was the second commit not needed before?

**Comment by encukou** [comment]
I usually run the server first.

**Comment by hroncok** [comment]
It still works for me without. What i the error you get? Do you have portingdb installed?

```
(venv) $ pip freeze | grep porting
-e git+git@github.com:fedora-python/portingdb.git@b25edf89461f616626c016c59c0af8579a7b9b72#egg=portingdb
```

Maybe we should docuement that instead?

**Comment by encukou** [comment]
No, I don't have it installed.
Changed to install `-e.` instead of setting PYTHONPATH. It's no longer such a tiny change now :)

**Pull request merged**
