### PR TITLE
Update Fedora data & Update for python2

### PR DESCRIPTION
**Pull request by irushchyshyn**
Update DNF plugin for python2 changes. @encukou could you please take a look if I covered everything?

Data update:

**idle -> missing (6)**

- ascend 
Retired in [commit](http://pkgs.fedoraproject.org/cgit/rpms/ascend.git/commit/ascend.spec?id=76c69dfc46c4e4251edb9d07f4097a9e747bfcae)
- freesteam
Retired in [commit](http://pkgs.fedoraproject.org/cgit/rpms/freesteam.git/commit/freesteam.spec?id=01117c39842661b57d63685881757ce3252984aa)
- python
Renamed to python2 [commit](http://pkgs.fedoraproject.org/cgit/rpms/python.git/commit/python.spec?id=cc6f5d97bf11ef467ce95c3343d3985c36dc0e8b)
- python-django-dajax
Dropped by maintainer [commit](http://pkgs.fedoraproject.org/cgit/rpms/python-django-dajax.git/commit/python-django-dajax.spec?id=a95446b2dbc25ad2d0bfda2d67bf6535fe84c76a)
- python-django-dajaxice
Dropped by maintainer [commit](http://pkgs.fedoraproject.org/cgit/rpms/python-django-dajaxice.git/commit/python-django-dajaxice.spec?id=dd83bc676e40e707611efc2f7898a1425cbe87c1)
- tktable
Dropped by maintainer [commit](http://pkgs.fedoraproject.org/cgit/rpms/tktable.git/commit/tktable.spec?id=881e890de5d52d8f146bd25d3e3ab2c4348a4c21)

**missing -> idle (1)**

- python2

**missing -> released (2)**

- fegistry
- gplugin

**released -> missing (1)**

- python-sphinx-theme-better
Dropped by maintainer [commit](http://pkgs.fedoraproject.org/cgit/rpms/python-sphinx-theme-better.git/commit/python-sphinx-theme-better.spec?id=a7c4ec0abd075fda8f0d487c9ac6fb20e4119696)

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
btw, proper URL for git repo is `https://src.fedoraproject.org/.....` ;)

**Comment by encukou** [comment]
Thanks @irushchyshyn. Since we have the entire data set available, testing is quite easy – the update didn't cause unwanted data changes, so everything should be fine :)

@ignatenkobrain, I don't see a wrong URL here, what am I missing?

**Comment by ignatenkobrain** [comment]
@encukou just saying that it's better to use `https://src.fp.o/` instead of `http://pkgs.fp.o`. src.fp.o is quite new and uses https://

**Comment by encukou** [comment]
@ignatenkobrain: are you talking about the link to the spec file from package pages like http://fedora.portingdb.xyz/pkg/arm-none-eabi-gdb/ (which I now fixed), or to something else?

**Pull request merged**
