### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
Update Fedora data

**idle** → **missing** (5)
- epylog
- mrpt
- python-tg-devtools
- python-tgcaptcha2
- python2-astropy

**idle** → **released** (2)
- buildbot (mhroncok maxed out)
- python-fedora (mhroncok :star2:)

**legacy-leaf** → **released** (7)
- ibus
- osbs-client
- python-flake8-import-order
- python-google-auth
- python-progress
- python-ryu
- python-sushy

**mispackaged** → **missing** (1)
- python-tgext-admin

**missing** → **idle** (1)
- resource-agents

**missing** → **released** (5)
- python-asgiref
- python-djangoql
- rust-cbindgen
- udica
- xfce4-panel-profiles

**released** → **legacy-leaf** (5)
- TurboGears2
- python-asttokens
- python-gearbox
- python-sprox
- python-tinyrpc

## Naming status changes

**named correctly** → **missing** (6)
- epylog
- mrpt
- python-tg-devtools
- python-tgcaptcha2
- python-tgext-admin
- python2-astropy

**requires misnamed** → **requires ok** (1)
- python-ryu

### CODE REVIEW

**Comment by hroncok** [comment]
```
WARNING: no RPMs in package python2-astropy
WARNING: no RPMs in package python2-matplotlib
WARNING: no RPMs in package python-tgcaptcha2
```

We should remove `python2-astropy` and `python-tgcaptcha2` from the overrides list.

**Comment by hroncok** [comment]
Pushed a commit. Not sure if worth regenerating the history entry (probably not). Merge at will (and check my commit please).

**Comment by encukou** [comment]
I had the same diff ready to commit, but you were faster :)

**Comment by hroncok** [comment]
I've cheated, used the GitHub web interface.

**Pull request merged**
