### PR TITLE
python-django-openid-auth Python 3 upstream available

### PR DESCRIPTION
**Pull request by ari3s**

### CODE REVIEW

**Comment by irushchyshyn** [comment]
Thanks @ari3s !
However, was Python 3 support for python-django-openid-auth announced anywhere?
Because I did not find any mention of it. And the source code still contains some py2 only syntax:
http://bazaar.launchpad.net/~ubuntuone-pqm-team/django-openid-auth/trunk/view/head:/django_openid_auth/views.py#L300
http://bazaar.launchpad.net/~ubuntuone-pqm-team/django-openid-auth/trunk/view/head:/django_openid_auth/views.py#L34
I may be missing something of course.

**Comment by ari3s** [comment]
Python 3 compatibility is mentioned at [PyPI](https://pypi.python.org/pypi/django-openid-auth/0.13) for 0.13 version. However, according to your finding, it looks that there are still gaps that I have not discovered.

**Comment by irushchyshyn** [comment]
Oh right, I see now that it is mentioned in `Py Version` indeed. However, it does not seem to be Python 3 ready yet, so let's wait a bit more for this one :)

**Comment by ari3s** [comment]
Version [0.14 at PyPI](https://pypi.python.org/pypi/django-openid-auth/0.14) contains Python 3 [fixes](http://bazaar.launchpad.net/~ubuntuone-pqm-team/django-openid-auth/trunk/revision/128), this version is finally Python 3 compatible.

**Comment by irushchyshyn** [comment]
Thanks @ari3s ! Created a [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1438714) for this package.

**Comment by ari3s** [comment]
There is already an existing Bugzilla bug [1273013](https://bugzilla.redhat.com/show_bug.cgi?id=1273013) where I have attached a new spec file.

**Comment by irushchyshyn** [comment]
I missed it. Closed as a duplicate. Thanks!

**Pull request closed without merging**
