### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
## Update Fedora data

**idle** → **missing** (6)
- libpoly
- python-TurboMail
- python-dateutil15
- python-nsdf
- python-turbojson
- python2-faulthandler

**idle** → **released** (4)
- nemo-extensions (leigh123linux 5→6)
- pdfposter (fab 7→8)
- sagemath (jjames 8→9)
- zypper (ngompa 2→3)

**legacy-leaf** → **missing** (2)
- python-camel
- python-deap

**legacy-leaf** → **released** (23)
- nautilus-python
- python-ansi2html
- python-assimulo
- python-cloudpickle
- python-collectd_systemd
- python-cycler
- python-editorconfig
- python-feedgenerator
- python-filelock
- python-gitlab
- python-grabbit
- python-htmlmin
- python-jira
- python-keystonemiddleware
- python-kiwisolver
- python-klusta
- python-mdp
- python-oslo-privsep
- python-oslo-reports
- python-oslo-versionedobjects
- python-pybtex-docutils
- xrootd
- z3

**mispackaged** → **legacy-leaf** (1)
- uwsgi

**mispackaged** → **released** (2)
- python-oslo-policy (churchyard, maxed out)
- python-oslo-rootwrap (churchyard, maxed out)

**missing** → **idle** (1)
- python2-matplotlib

**missing** → **released** (7)
- freecell-solver
- python-PyLEMS
- python-datadog
- python-duecredit
- python-repomd
- python-visionegg-quest
- signon-glib

**released** → **legacy-leaf** (13)
- brial
- python-ZODB3
- python-flask-autoindex
- python-fpylll
- python-gmpy2
- python-hdfs
- python-httmock
- python-latexcodec
- python-notebook :eyes: 
- python-oslo-cache
- python-pycadf
- python-pytest-capturelog
- python-scikit-learn

**released** → **missing** (2)
- openms
- stratis-cli

## Naming status changes

**missing** → **requires misnamed** (2)
- kde-connect
- qdigidoc

**named correctly** → **missing** (10)
- libpoly
- openms
- python-TurboMail
- python-camel
- python-dateutil15
- python-deap
- python-nsdf
- python-turbojson
- python2-faulthandler
- stratis-cli

**requires misnamed** → **requires ok** (5)
- qgis
- python-collectd_systemd
- python-oslo-policy
- python-oslo-privsep
- python-oslo-versionedobjects

### CODE REVIEW

**Comment by hroncok** [comment]
sagemath :tada: :balloon: :birthday:

**Comment by hroncok** [comment]
python2-matplotlib should be dropped, not idle

**Comment by encukou** [comment]
> python2-matplotlib should be dropped, not idle

It's marked as such later. The diff is only for `fedora.json`.

**Comment by hroncok** [comment]
New bugs are open.

**Pull request merged**
