### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
**idle** → **missing** (1)
- direwolf (BR fix)

**idle** → **py3-only** (5) ♥
- quantum-espresso (marcindulak 2→3)
- sugar-finance (pbrobinson ∞)
- sugar-stopwatch (chimosky 8→9)
- sugar-turtleart (chimosky 9→10 :3rd_place_medal:)
- sugar-words (chimosky 10→11)

**missing** → **py3-only** (8)
- arbor
- fonts-rpm-macros
- pre-commit
- python-contextily
- python-mapclassify
- python-mercantile
- python-pytest-astropy-header
- python-pytest-randomly

**py3-only** → **missing** (3)
- python-traceback2 (retired)
- slack-cleaner (retired orphan)
- vault (retired)

### CODE REVIEW

**Comment by hroncok** [comment]
quantum-espresso buildrequires numpy (python2-numpy) :(

**Comment by hroncok** [comment]
> numpy (python2-numpy)

https://bugzilla.redhat.com/show_bug.cgi?id=1734445#c4

**Comment by encukou** [comment]
We don't track that kind of dependency, the maintainer is on their own to coordinate this :(

Here's another one, `viewmtn` depends on `python2-cheetah` and `python2-mod_wsgi`: https://bugzilla.redhat.com/show_bug.cgi?id=1807575

**Comment by hroncok** [comment]
> We don't track that kind of dependency, 

I know. I just pointed out something we should report.

**Pull request merged**
