### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
**idle** → **missing** (2)
- python2-jsonschema
- ssh-installkeys

**idle** → **py3-only** (3) ♥
- duplicity (limb 10→11)
- fleet-commander-client (ogutierrez 0→1 :1st_place_medal: )
- totpcgi (kevin 3→4)

**legacy-leaf** → **py3-only** (2)
- PyPAM
- python-pytest-watch

**missing** → **py3-only** (11)
- foliate
- python-acora
- python-confuse
- python-hpilo
- python-ns1-python
- python-nudepy
- python-pytest-lazy-fixture
- python-sphinx-notfound-page
- python-virtualbmc
- pythran
- sshexport

**released** → **legacy-leaf** (5)
- PyDrive
- python-dbusmock
- python-dropbox
- python-passlib
- python-pyotp

## Naming status changes

**named correctly** → **missing** (2)
- python2-jsonschema
- ssh-installkeys

**requires misnamed** → **missing** (19)
- blitz *(python-unversioned-command)*
- crun *(python-unversioned-command)*
- farstream02 *(python2-devel)*
- gstreamer-plugins-good
- htop *(python-unversioned-command)*
- hyperscan *(python-unversioned-command)*
- json4s *(python-unversioned-command)*
- kdepim3 *(python2-devel)*
- libclc *(python-unversioned-command)*
- liquidwar *(python-unversioned-command)*
- maxima *(python-unversioned-command)*
- mingw-qpid-cpp *(python2-devel)*
- mingw-wine-gecko *(python-unversioned-command)*
- mongo-c-driver *(python-unversioned-command)*
- mozc *(python-unversioned-command)*
- sbt *(python-unversioned-command)*
- seamonkey *(python-unversioned-command)*
- spring *(python2-devel)*
- udis86 *(python-unversioned-command)*

**requires misnamed** → **requires ok** (3)
- grass
- qct
- vegastrike

### CODE REVIEW

**Comment by hroncok** [comment]
Do we need to update the code the handle misnamed dependencies on Python 3?

**Comment by encukou** [comment]
I don't think we need to track that.

**Comment by hroncok** [comment]
Not until we start dealing with Python 4 :grin:

**Comment by hroncok** [comment]
WARNING: no RPMs in package python2-jsonschema

**Comment by encukou** [comment]
> ```
> WARNING: no RPMs in package python2-jsonschema
> ```

Oops, sorry, forgot to push that one!

**Pull request merged**
