### PR TITLE
Packages Python 3 upstream available

### PR DESCRIPTION
**Pull request by ari3s**
- [ ] gfal2-python [[https://its.cern.ch/jira/browse/DMC-875](https://its.cern.ch/jira/browse/DMC-875)]
- [ ] gnatcoll [[http://libre.adacore.com/developers/development-log-single/NF-15-L619-031-gnatcoll](http://libre.adacore.com/developers/development-log-single/NF-15-L619-031-gnatcoll)]
- [ ] gnucash [[Documentation - chapter 2](https://media.readthedocs.org/pdf/piecash/latest/piecash.pdf)]
- [ ] hivex [[Python 3 package already available in Ubuntu](https://www.ubuntuupdates.org/package/core/zesty/universe/base/python3-hivex)]

### CODE REVIEW

**Comment by encukou** [comment]
The documentation you linked for GnuCash is for `piecash`, a different project.

**Comment by irushchyshyn** [comment]
Started to create tickets:
gfal2-python - https://bugzilla.redhat.com/show_bug.cgi?id=1453168
gnatcoll - https://bugzilla.redhat.com/show_bug.cgi?id=1453185
hivex - https://bugzilla.redhat.com/show_bug.cgi?id=1453189

**Comment by ari3s** [comment]
@encukou: You are right, I was confused by the name. The package is still in Python 2 only. Thank you for the check.

**Comment by encukou** [comment]
Bugzillas are filed for the rest, and they're marked as mispackaged. 

Thank you, Honza and Irina!

**Pull request closed without merging**
