### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
**idle** → **mispackaged** (1)
- trace-cmd ([stray shebang?](https://github.com/fedora-python/portingdb/pull/559))

**idle** → **missing** (4)
- Spawning
- planner
- python-anyvc
- tennix

**idle** → **py3-only** (1) ♥
- vdrift (limb ∞)

**legacy-leaf** → **missing** (1)
- python-coveralls

**legacy-leaf** → **py3-only** (2)
- google-api-python-client
- uwsgi

**mispackaged** → **missing** (1)
- dreampie

**mispackaged** → **released** (1) ♥
- python-pmw (churchyard ∞)

**missing** → **idle** (1)
- python2-numpy (→ dropped)

**missing** → **py3-only** (15)
- dynamic-wallpaper-editor
- hydrapaper
- libmodulemd1
- novnc
- openqa
- osbuild
- python-deprecated
- python-freecell_solver
- python-vevents
- sevmgr
- simcrs
- simfqt
- stdair
- travelccm
- xfce4-screensaver

**py3-only** → **missing** (17)
- kaadbg
- mkdocs
- mkdocs-alabaster
- mkdocs-basic-theme
- mkdocs-bootstrap
- mkdocs-bootswatch
- mkdocs-cinder
- mkdocs-material
- pintail
- python-googletrans
- python-honcho
- python-pg8000
- python-rauth
- python-seesaw
- python-windtalker
- python3-curses_ex
- python3-pyjf3

**released** → **legacy-leaf** (5)
- python-dmidecode
- python-enchant
- python-hgdistver
- python-subvertpy
- python-websockify

**released** → **py3-only** (5)
- numpy
- python-stomper
- python-uritemplate
- python-virtualenv
- setools

Naming status changes
---------------------

**misnamed** → **missing** (1)
- dreampie

**named correctly** → **missing** (22)
- Spawning
- kaadbg
- mkdocs
- mkdocs-alabaster
- mkdocs-basic-theme
- mkdocs-bootstrap
- mkdocs-bootswatch
- mkdocs-cinder
- mkdocs-material
- pintail
- planner
- python-anyvc
- python-coveralls
- python-googletrans
- python-honcho
- python-pg8000
- python-rauth
- python-seesaw
- python-windtalker
- python3-curses_ex
- python3-pyjf3
- tennix

**requires misnamed** → **missing** (3)
- LogService
- geany-plugins
- fawkes

**requires misnamed** → **requires ok** (6)
- python-fedora
- tito
- writetype
- dmlite
- calibre
- swatchbooker

### CODE REVIEW

**Comment by hroncok** [comment]
Are we loosing information with the: requires misnamed → missing changes due to https://fedoraproject.org/wiki/Changes/Python_means_Python3 ?

See also:

https://bugzilla.redhat.com/show_bug.cgi?id=1737225
https://bugzilla.redhat.com/show_bug.cgi?id=1737222
https://bugzilla.redhat.com/show_bug.cgi?id=1737224
https://bugzilla.redhat.com/show_bug.cgi?id=1737226

**Comment by encukou** [comment]
I guess we are.
Should we handle these somehow?
Should we track this specially?
Would a "requires misnamed → missing" list for the last N months be enough to work with?

**Comment by hroncok** [comment]
What if we do it this way (before this PR is merged):

 * we export the current list of requires misnamed relations to a permanent file in git
  * (as triplets of <whatrequires>, <ambigious_requires>, <proper_requires>)
 * we consider dependencies on <ambigious_requires> from that list as dependencies on <proper_requires>
 * we file bugzillas as soon as requires misnamed → missing/requires ok happens

**Comment by encukou** [comment]
Go ahead!
You might even want to go back in history a bit for the initial triplet list.

**Comment by hroncok** [comment]
I'll go back to before we updated %python_provide

**Comment by hroncok** [comment]
Unfortunately we don't have those data in git, but I'll mage somehow, maybe querying fedora 30 instead.

**Comment by hroncok** [comment]
https://github.com/fedora-python/portingdb/pull/563

**Comment by encukou** [comment]
Good to go now?
I should do another update after this, since it looks like the compose composed.

**Comment by hroncok** [comment]
I think we should just drop this and obsolete it by the next update not to move packages requires misnamed → requires ok → requires misnamed. Is that OK?

**Comment by encukou** [comment]
OK

**Pull request closed without merging**
