### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
**idle** → **missing** (1)
- gstreamer1-plugins-good

**legacy-leaf** → **py3-only** (1)
- python-pycryptodomex (churchyard ∞)

**missing** → **py3-only** (82)
- RediSearch
- academic-admin
- andriller
- bmake
- bst-external
- cvise
- dnsgen
- flexiblas
- google-auth-httplib2
- gst-editing-services
- hfg-gmuend-openmoji-fonts
- jgmenu
- ldapdomaindump
- ldeep
- libhandy1
- libvirt-test-API
- mingw-python-certifi
- mingw-python-flask
- mingw-python-itsdangerous
- mingw-python-jinja2
- mingw-python-pillow
- mingw-python-requests
- mingw-python-werkzeug
- mkdocs-bootswatch
- modulemd-tools
- monsterz
- python-adb
- python-aiogqlc
- python-aiohue
- python-aiomultiprocess
- python-angr
- python-ansiwrap
- python-claripy
- python-commandparse
- python-django-contrib-comments
- python-django-uuslug
- python-fastprogress
- python-flask-compress
- python-git-revise
- python-google-auth-oauthlib
- python-graphene
- python-graphql-core
- python-graphql-relay
- python-hass-data-detective
- python-hstspreload
- python-httpcore
- python-httpx
- python-jaraco-collections
- python-jaraco-text
- python-jose
- python-korean-lunar-calendar
- python-kyotocabinet
- python-markdown-math
- python-masscan
- python-mysqlclient
- python-nanoid
- python-niapy
- python-opencensus
- python-opentelemetry
- python-ouimeaux
- python-pebble
- python-promise
- python-publicsuffix2
- python-py-gql
- python-pymata-express
- python-pysignals
- python-pytest-sanic
- python-pytzdata
- python-sphinxcontrib-zopeext
- python-sqlalchemy_schemadisplay
- python-ssdp
- python-textwrap3
- python-typedecorator
- python-zstandard
- rust-xcb
- scanless
- setzer
- sipvicious
- snallygaster
- socialscan
- theme-switcher
- trojan

**py3-only** → **missing** (5)
- js-zlib
- kajongg
- pyephem
- python-azure-sdk
- python-zope-i18nmessageid

**released** → **legacy-leaf** (1)
- python-psutil (used for Chromium remoting, which [was](https://src.fedoraproject.org/rpms/chromium/c/7fd8d4b5edac81cb4cdebe3470b8daafeb48ecaa?branch=master) [disabled](https://src.fedoraproject.org/rpms/chromium/blob/7fd8d4b5edac81cb4cdebe3470b8daafeb48ecaa/f/chromium.spec#_20) for Chromium 83)

**released** → **missing** (1)
- ghdl (sharkcz ∞)

### CODE REVIEW

**Comment by hroncok** [comment]
Do we give badges for idle -> missing? I suppose the ship has sailed, but I have a feeling (arguably rusty) that we don't.

**Comment by hroncok** [comment]
@spotrh Do we keep python2-psutil for now in case chromium remoting starts working again?

**Comment by encukou** [comment]
> Do we give badges for idle -> missing? I suppose the ship has sailed, but I have a feeling (arguably rusty) that we don't.

Ah, right, we don't. I haven't given it out yet.

**Comment by hroncok** [comment]
> Ah, right, we don't. I haven't given it out yet.

Same for ghdl then.

Other than that, looks good and ship at will.

**Comment by encukou** [comment]
Thanks.

**Pull request merged**
