### PR TITLE
Allow to specify repo for check drops

### PR DESCRIPTION
**Pull request by hroncok**
I have no better idea how to change click default / required of one option based on another option's provided value.

### CODE REVIEW

**Comment by encukou** [comment]
Make the default `None`, and update it if you get None. Would that work?

**Comment by hroncok** [comment]
Will try.

**Comment by hroncok** [comment]
Amended.

**Comment by encukou** [comment]
Looks good! I didn't try it yet though.

**Comment by hroncok** [comment]
It works OK for me so far.

**Pull request merged**
