### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
**idle** → **missing** (2)
- sugar-castle (retired)
- sugar-countries (retired)

**missing** → **idle** (2)
- openjfx (https://bugzilla.redhat.com/show_bug.cgi?id=1886933)
- sems (https://bugzilla.redhat.com/show_bug.cgi?id=1886932)

**missing** → **py3-only** (25)
- cozy
- libecpint
- memavaild
- postfix-mta-sts-resolver
- pylibgamerzilla
- python-aioeafm
- python-async-upnp-client
- python-crashtest
- python-didl-lite
- python-easyco
- python-ee
- python-enturclient
- python-fastapi
- python-gettext
- python-google-i18n-address
- python-inject
- python-manatools
- python-nrf24
- python-pytapo
- python-pyvlx
- python-stackprinter
- python-starlette
- python-vcversioner
- python-zope-i18nmessageid
- sudo

**py3-only** → **missing** (1)
- pyee

### CODE REVIEW

**Comment by hroncok** [comment]
BTW I've noticed that the new bugzillas say:

> In Fedora, it's now provided from the deprecated compat package `python27`

Could you update that to `python2.7` in your template?

**Comment by encukou** [comment]
I've made a template, and updated it. Thanks!

**Comment by hroncok** [comment]
I was curious why sudo suddenly links to libpython. https://www.sudo.ws/man/1.9.3/sudo_plugin_python.man.html

**Comment by encukou** [comment]
Wow, sudo even has a logo!

**Comment by hroncok** [comment]
I guess it's from "sudo, make me a sandwich".

**Pull request merged**
