### PR TITLE
⏻ Add "orphaned" badges to package names

### PR DESCRIPTION
**Pull request by encukou**
image

I also had some code to show how long these were orphaned, but it takes too long to update (by querying pagure).

### CODE REVIEW

**Comment by hroncok** [comment]
Is the "upper index" position intentional?




I'd appreciate if the information was also presented on the detail page of the orphaned package. Maybe even more verbosely. Byt this is not a blocker.

**Comment by encukou** [comment]
> Is the "upper index" position intentional?

Yes*.

<i>*⁾ I wanted this to look like a note.</i>

> I'd appreciate if the information was also presented on the detail page of the orphaned package. 

Added.

**Comment by hroncok** [comment]
I'll see if I can publish the packages/weeks from https://churchyard.fedorapeople.org/orphans.txt as json.

**Comment by hroncok** [comment]
See https://churchyard.fedorapeople.org/orphans.json

**Comment by encukou** [comment]
See https://github.com/fedora-python/portingdb/pull/611 :)

**Pull request merged**
