### PR TITLE
Update Fedora data & remove orphan data

### PR DESCRIPTION
**Pull request by encukou**
The `orphans.json` report is no longer accessible, and the data isn't all that useful when portingdb doesn't update all that often.

**mispackaged** → **py3-only** (1) ♥
- nanopb (https://bugzilla.redhat.com/show_bug.cgi?id=2228109 - regression fixed)

**missing** → **idle** (1)
- flatpak-builder (https://bugzilla.redhat.com/show_bug.cgi?id=2249819)

**missing** → **py3-only** (246)
- ansible-builder
- ardour8
- bcachefs-tools
- bindep
- blake3
- byebyebios
- chirp
- cinnamon-session
- clang17
- coin-or-HiGHS
- compiler-rt17
- conda-build
- coreutils
- cp2k
- cpeditor
- cramjam-cli
- dnsconfd
- dotnet8.0
- emacspeak
- f3d
- fastfetch
- fawltydeps
- fedora-distro-aliases
- gdm
- ghc9.8
- gnome-ponytail-daemon
- go-vendor-tools
- ibus-array
- icecat
- intel-media-driver-free
- ipa-hcc
- kf6-kapidox
- kvirc
- lcov
- lfortran
- libicu73
- liblc3
- libmamba
- libpeas1
- libsecret
- linux-sysinfo-snapshot
- llvm17
- lusol
- mailman3-fedmsg-plugin-schemas
- mariadb10.11
- mat2
- mingw-python-blinker
- mmtests
- mupdf
- obs-cef
- open-vmdk
- pagure-exporter
- plasma-bigscreen
- plasma-workspace
- postgresql15
- postgresql16
- pybind11-json
- python-APScheduler
- python-aiohttp-oauthlib
- python-aioquic
- python-aioruckus
- python-aiostream
- python-archspec
- python-argparse-dataclass
- python-arm-preprocessing
- python-azure-monitor-query
- python-beartype
- python-bioframe
- python-bioread
- python-boltons
- python-chalice
- python-cmap
- python-coincidence
- python-colcon-override-check
- python-colorthief
- python-commoncode
- python-conda-index
- python-conda-inject
- python-conda-libmamba-solver
- python-container-inspector
- python-cramjam
- python-crc32c
- python-cvdupdate
- python-debian-inspector
- python-dirhash
- python-django4.2
- python-docopt-ng
- python-domdf-python-tools
- python-dparse2
- python-esbonio
- python-expandvars
- python-expecttest
- python-extractcode
- python-extractcode-7z
- python-extractcode-libarchive
- python-fedora-sig-onboard
- python-fingerprints
- python-flask-session
- python-flexparser
- python-fontquery
- python-ftfy
- python-ftputil
- python-gbulb
- python-gemfileparser2
- python-geodatasets
- python-google-cloud-monitoring
- python-hatch-requirements-txt
- python-hiredis
- python-hypercorn
- python-imapclient
- python-inquirer
- python-intbitset
- python-jaraco-test
- python-jsonformatter
- python-jsonschema-path
- python-jsonstreams
- python-llama-cpp-python
- python-lqrt
- python-lsprotocol
- python-lxml-html-clean
- python-mailman-hyperkitty
- python-mailman-web
- python-memray
- python-menuinst
- python-mpd2
- python-murmurhash
- python-nh3
- python-nifti-mrs
- python-normality
- python-openneuro
- python-opentelemetry-propagator-aws-xray
- python-opentelemetry-resource-detector-azure
- python-opentelemetry-sdk-extension-aws
- python-packvers
- python-parameter-expansion-patched
- python-pip-requirements-parser
- python-pkginfo2
- python-platformio
- python-plugincode
- python-py-tes
- python-pyaes
- python-pyahocorasick
- python-pyasn
- python-pycomposefile
- python-pyconify
- python-pydantic-extra-types
- python-pydantic-settings
- python-pyfiglet
- python-pygls
- python-pygmars
- python-pylsqpack
- python-pymaven-patch
- python-pyngus
- python-pynose
- python-pyside6
- python-pyspellchecker
- python-pytest-home
- python-pytest-lsp
- python-pytest-qt
- python-python-ulid
- python-pyuca
- python-pyzstd
- python-qudida
- python-rpmautospec-core
- python-rpmautospec-koji
- python-saneyaml
- python-sgqlc
- python-simple-pid
- python-simple-websocket
- python-snakemake-executor-plugin-cluster-generic
- python-snakemake-executor-plugin-cluster-sync
- python-snakemake-executor-plugin-kubernetes
- python-snakemake-executor-plugin-slurm
- python-snakemake-executor-plugin-slurm-jobstep
- python-snakemake-executor-plugin-tes
- python-snakemake-interface-common
- python-snakemake-interface-executor-plugins
- python-snakemake-interface-report-plugins
- python-snakemake-interface-storage-plugins
- python-snakemake-storage-plugin-azure
- python-snakemake-storage-plugin-fs
- python-snakemake-storage-plugin-ftp
- python-snakemake-storage-plugin-gcs
- python-snakemake-storage-plugin-http
- python-snakemake-storage-plugin-s3
- python-snakemake-storage-plugin-zenodo
- python-spdx-tools
- python-sphinx-argparse-cli
- python-sphinx-jsonschema
- python-sphinx-lint
- python-sqlalchemy1.4
- python-superqt
- python-sysrsync
- python-tensile
- python-tensordict
- python-tiktoken
- python-timelib
- python-tiny-proxy
- python-torch
- python-torchaudio
- python-torchdata
- python-torchtext
- python-torchvision
- python-trx-python
- python-typecode
- python-typecode-libmagic
- python-types-pygments
- python-types-setuptools
- python-untangle
- python-uritools
- python-urlpy
- python-vedo
- python-vhacdx
- python-willow
- python-wsgidav
- python-xarray-einstats
- python-xdfile
- python-xkbregistry
- python-zlib-ng
- python-zstarfile
- qtile
- re2c
- renderdoc
- rpm-spec-language-server
- ruff
- ruff-lsp
- rust-add-determinism
- rust-jiter
- rust-os_pipe
- rust-pyo3-build-config
- rust-pyo3-build-config0.20
- rust-pyo3-ffi0.19
- rust-pyo3-ffi0.20
- rust-roxmltree0.18
- scip
- soplex
- ssh-audit
- sway-contrib
- syncplay
- syndication-domination
- virtme-ng
- vrpn
- vulkan-utility-libraries
- xr-hardware
- xwayland-run
- yasm

**py3-only** → **missing** (143)
- 0ad
- OpenIPMI
- aiodnsbrute
- anaconda-user-help
- ccnet
- clang11
- clang14
- dotnet7.0
- fedmod
- foliate
- heat-cfntools
- hfg-gmuend-openmoji-fonts
- hgview
- ibus-bogo
- icaro
- iotop
- kernel-tools
- kf5-kapidox
- kismon
- komikku
- kwin
- libicu71
- libicu72
- libmodulemd1
- llvm7.0
- llvm8.0
- mariadb
- memavaild
- mingw-python-pygments
- mkosi-initrd
- mkosi14
- nutty
- obs-service-cargo_vendor
- onboard
- openclonk
- osbuild-composer
- pg_view
- pipenv
- plasma-desktop
- plasma-firewall
- postgresql
- prelockd
- pseudo
- python-GridDataFormats
- python-aiomqtt
- python-astropy-helpers
- python-autoprop
- python-colorcet
- python-compressed-rtf
- python-cython0.29
- python-elpy
- python-esphomeflasher
- python-fdb
- python-flask-htmlmin
- python-google-cloud-access-approval
- python-google-cloud-access-context-manager
- python-google-cloud-api-gateway
- python-google-cloud-apigee-connect
- python-google-cloud-appengine-admin
- python-google-cloud-asset
- python-google-cloud-automl
- python-google-cloud-bigquery
- python-google-cloud-bigquery-connection
- python-google-cloud-bigquery-datatransfer
- python-google-cloud-bigquery-reservation
- python-google-cloud-bigquery-storage
- python-google-cloud-bigtable
- python-google-cloud-billing
- python-google-cloud-billing-budgets
- python-google-cloud-build
- python-google-cloud-common
- python-google-cloud-container
- python-google-cloud-containeranalysis
- python-google-cloud-data-fusion
- python-google-cloud-datacatalog
- python-google-cloud-dataproc
- python-google-cloud-dataproc-metastore
- python-google-cloud-debugger-client
- python-google-cloud-deploy
- python-google-cloud-dlp
- python-google-cloud-dms
- python-google-cloud-domains
- python-google-cloud-filestore
- python-google-cloud-firestore
- python-google-cloud-functions
- python-google-cloud-iam
- python-google-cloud-kms
- python-google-cloud-org-policy
- python-google-cloud-os-config
- python-google-cloud-private-ca
- python-google-cloud-pubsub
- python-google-cloud-redis
- python-google-cloud-shell
- python-google-cloud-source-context
- python-google-cloud-spanner
- python-google-cloud-testutils
- python-grafeas
- python-htmlmin
- python-jsonschema-spec
- python-jupyter-collaboration
- python-jupyter-server-fileid
- python-jupyter-ydoc
- python-kaitaistruct
- python-limits
- python-maya
- python-metaextract
- python-mysql
- python-openopt
- python-oslo-sphinx
- python-param
- python-pep517
- python-pyct
- python-pymoc
- python-pytest-bdd5
- python-pyvhacd
- python-ratelimiter
- python-signature-dispatch
- python-snipeit
- python-sphinx_reredirects
- python-sphinxcontrib-applehelp
- python-sphinxcontrib-jsmath
- python-subvertpy
- python-timeunit
- python-twitter
- python-vagrantpy
- python-vecrec
- python-wtforms-sqlalchemy
- python-y-py
- python-ypy-websocket
- python3-typed_ast
- remctl
- rust-pyo3-ffi0.16
- rust-pyo3-ffi0.18
- rust-pyo3_0.15
- rust-python3-sys
- seqan
- seqan2
- sphinxbase
- streamtuner
- telepathy-logger-qt
- telepathy-qt
- virtme
- wget

### CODE REVIEW

**Comment by hroncok** [comment]
> The orphans.json report is no longer accessible...

It was moved to https://a.gtmx.me/orphans/orphans.json

**Comment by encukou** [comment]
Does the new location work for you?

**Comment by hroncok** [comment]
Oh, the structure has changed a bit. I don't think we necessarily need to adapt, I am OK to remove it.

**Review by hroncok — APPROVED** [review]

**Comment by encukou** [comment]
Ah, gtmx.me is up now!
But, we aren't really waiting for any orphan removals now, and with months between updates, the data would usually be too stale to use anyway.

**Pull request merged**
