### PR TITLE
Track legacy leaf Python 2 packages among released

### PR DESCRIPTION
**Pull request by irushchyshyn**
Actually we have started to collect BuildRequires of Python packages in #319.
What was left is tracking any non-Python packages that require portingdb packages.

Scope:
- [x] For each RPM in a package, collect non-Python packages which depend on it (both build time and runtime). This adds a new field to `fedora.json` in the `rpms` section:

```
"non_python_requirers": {
          "build_time": [],
          "run_time": []
        },
```

- [x] Add a new status `legacy-leaf`, which means that all Python 2 RPMs in a package are not required by anything in Fedora (that RPMs will have a `legacy_leaf: True` field). This status will be applied only to `Released` packages (those that package both Python versions of the package).
- [x] Add a new status to the index page on UI (between Released and Py3 only)
Index page top:
image
Legacy-leaf section:
image

- [x] Display which RPM is a `legacy_leaf`
image

Further optional:
(Not to make this PR even bigger, these are to be done in separate PRs)
- [ ] Display BuildRequires on package page
- [ ] Display non-Python requirers on package page

---
<details>
  <summary>Fedora data update</summary>

**released -> legacy-leaf (710)**
- APLpy
- ATpy
- COPASI
- GeographicLib
- NLopt
- adapt
- ansible-inventory-grapher
- ansible-review
- argparse-manpage
- assimp
- atomic-reactor
- aubio
- botan
- bpython
- brltty
- cairo-dock-plug-ins
- cantor
- capstone
- caribou
- catfish
- clufter
- clustershell
- collectd-ceilometer-plugin
- compose-utils
- conda
- conu
- cryptsetup
- csdiff
- dlib
- dnf-plugins-extras
- dnfdaemon
- etckeeper
- fence-agents
- firewalld
- flann
- fontdump
- gcc-python-plugin
- gdcm
- gerrymander
- ginga
- git
- glances
- gpaw
- gprof2dot
- gpsd
- gtts
- hivex
- i2c-tools
- ibus
- imgbased
- iscsi-initiator-utils
- isomd5sum
- jabberpy
- keycloak-httpd-client-install
- lcm
- ldns
- libcap-ng
- libforensic1394
- libfreenect
- libftdi
- libkml
- liblinear
- liblouis
- libnl3
- libnuml
- libproxy
- libsbml
- libsedml
- libsolv
- libssh2-python
- libstoragemgmt
- libyui-bindings
- link-grammar
- mathgl
- module-build-service-copr
- moose
- mraa
- nbdkit
- omniORBpy
- opencv
- openms
- openslide-python
- patool
- petsc4py
- pkgwat
- portmidi
- prelude-correlator
- prewikka
- ptpython
- pungi
- py4j
- pycanberra
- pychromecast
- pycolumnize
- pycscope
- pyephem
- pyfits
- pygrib
- pygsl
- pyhunspell
- pyjokes
- pyke
- pykka
- pyliblo
- pymilia
- pymodbus
- pyodbc
- pyosmium
- pyowm
- pyqtrailer
- pyscard
- python-APScheduler
- python-CacheControl
- python-ECPy
- python-Mastodon
- python-MultipartPostHandler2
- python-Naked
- python-PyLink
- python-PyRSS2Gen
- python-Pympler
- python-XStatic-Angular
- python-XStatic-Angular-Bootstrap
- python-XStatic-Angular-FileUpload
- python-XStatic-Angular-Gettext
- python-XStatic-Angular-Mock
- python-XStatic-Angular-lrdragndrop
- python-XStatic-Bootstrap-Datepicker
- python-XStatic-D3
- python-XStatic-Font-Awesome
- python-XStatic-Hogan
- python-XStatic-JQuery-Migrate
- python-XStatic-JQuery-TableSorter
- python-XStatic-JQuery-quicksearch
- python-XStatic-JSEncrypt
- python-XStatic-Jasmine
- python-XStatic-Magic-Search
- python-XStatic-QUnit
- python-XStatic-Rickshaw
- python-XStatic-Spin
- python-XStatic-bootswatch
- python-XStatic-jquery-ui
- python-XStatic-mdi
- python-XStatic-roboto-fontface
- python-XStatic-smart-table
- python-XStatic-termjs
- python-abclient
- python-adduserpath
- python-afl
- python-alchimia
- python-alsaaudio
- python-altgraph
- python-amico
- python-ansi
- python-ansi2html
- python-ansible-tower-cli
- python-ansicolor
- python-ansicolors
- python-anyconfig
- python-aodhclient
- python-asciitable
- python-asciitree
- python-assimulo
- python-astral
- python-astroML-addons
- python-astroquery
- python-atomicwrites
- python-auth-credential
- python-autopep8
- python-azure-storage
- python-backports-csv
- python-baker
- python-barbicanclient
- python-bash8
- python-bashate
- python-batinfo
- python-bintrees
- python-bitmath
- python-bitstring
- python-blivet
- python-bloom
- python-bottle-sqlite
- python-btchip
- python-bz2file
- python-cachez
- python-camel
- python-cartopy
- python-catkin_lint
- python-catkin_tools
- python-cattrs
- python-ccdproc
- python-ceilometerclient
- python-ceilometermiddleware
- python-cerberus
- python-cerealizer
- python-certbot-apache
- python-certbot-dns-cloudflare
- python-certbot-dns-cloudxns
- python-certbot-dns-digitalocean
- python-certbot-dns-dnsimple
- python-certbot-dns-dnsmadeeasy
- python-certbot-dns-google
- python-certbot-dns-luadns
- python-certbot-dns-nsone
- python-certbot-dns-rfc2136
- python-certbot-dns-route53
- python-certbot-nginx
- python-characteristic
- python-citeproc-py
- python-click-log
- python-click-threading
- python-clint
- python-cloud-sptheme
- python-clyent
- python-cma
- python-cmigemo
- python-colorlog
- python-colorspacious
- python-colour-runner
- python-concurrentloghandler
- python-configshell
- python-congressclient
- python-contexttimer
- python-cotyledon
- python-couchdb
- python-cradox
- python-cram
- python-croniter
- python-csvkit
- python-cursive
- python-cvss
- python-cytoolz
- python-daiquiri
- python-dbf
- python-deap
- python-debrepo
- python-deltasigma
- python-dialog
- python-diff-cover
- python-diff-match-patch
- python-dill
- python-distlib
- python-django-ckeditor
- python-django-cors-headers
- python-django-extensions
- python-django-fas
- python-django-federated-login
- python-django-helpdesk
- python-django-jsonfield
- python-django-markdown2
- python-django-openid-auth
- python-django-pgjson
- python-django-post_office
- python-django-pylibmc
- python-django-sekizai
- python-django-select2
- python-django-setuptest
- python-django-south
- python-django-tinymce
- python-djvulibre
- python-dockerpty
- python-docx
- python-drat
- python-easyargs
- python-editorconfig
- python-elasticsearch
- python-email_reply_parser
- python-emcee
- python-enlighten
- python-epdb
- python-epi
- python-epub
- python-evdev
- python-events
- python-evic
- python-f5-icontrol-rest
- python-factory-boy
- python-falcon
- python-fdb
- python-filelock
- python-filetype
- python-firkin
- python-fitsio
- python-flake8-import-order
- python-flask-assets
- python-flask-bootstrap
- python-flask-cache
- python-flask-classy
- python-flask-debugtoolbar
- python-flask-mako
- python-flask-oauth
- python-flask-principal
- python-flask-restless
- python-flask-rstpages
- python-flask-whooshee
- python-flock
- python-fmn-sse
- python-fn
- python-fontname
- python-fpylll
- python-fsmonitor
- python-fuckit
- python-furl
- python-fuzzyfinder
- python-gabbi
- python-gatspy
- python-gccinvocation
- python-gensim
- python-geoip2
- python-geopandas
- python-gfm
- python-giacpy
- python-gitapi
- python-github3py
- python-glob2
- python-glyphsLib
- python-gnocchiclient
- python-gntp
- python-googletrans
- python-gradunwarp
- python-grafyaml
- python-graphitesend
- python-gunicorn
- python-hdfs
- python-hexdump
- python-hgapi
- python-honcho
- python-htmlmin
- python-hwdata
- python-i3ipc
- python-idstools
- python-igraph
- python-importanize
- python-importmagic
- python-influxdb
- python-inifile
- python-instant
- python-interfile
- python-invocations
- python-iowait
- python-ipdb
- python-ipgetter
- python-iptables
- python-iso639
- python-ivi
- python-j1m.sphinxautointerface
- python-jaydebeapi
- python-jcconv
- python-jellyfish
- python-jenkins-job-builder
- python-jenkinsapi
- python-jinja2-cli
- python-jnius
- python-jsmin
- python-jsonmodels
- python-jsonrpclib
- python-justbytes
- python-k8sclient
- python-kaptan
- python-keystonemiddleware
- python-kiwisolver
- python-klusta
- python-krbcontext
- python-kubernetes
- python-lasagne
- python-lazr-config
- python-lazr-smtptest
- python-lazyarray
- python-libarchive-c
- python-librosa
- python-libtmux
- python-line_profiler
- python-livereload
- python-llfuse
- python-lmiwbem
- python-logbook
- python-logging-tree
- python-logzero
- python-ludolph-zabbix
- python-lupa
- python-ly
- python-lzo
- python-m2r
- python-magnumclient
- python-manilaclient
- python-maps
- python-marathon
- python-markups
- python-marrow-mailer
- python-marshmallow-enum
- python-martian
- python-mdp
- python-messaging
- python-metar
- python-mglob
- python-microversion-parse
- python-mlpy
- python-mne
- python-more-itertools
- python-moss
- python-mpd
- python-mpd2
- python-mtg
- python-munkres
- python-murano-pkg-check
- python-music21
- python-mygpoclient
- python-myhdl
- python-natsort
- python-neovim
- python-netdiff
- python-netjsonconfig
- python-netlib
- python-netmiko
- python-networkmanager
- python-ngram
- python-nipy
- python-nixio
- python-nmap
- python-nmrglue
- python-nodeenv
- python-nose-parameterized
- python-nose-progressive
- python-nose-testconfig
- python-nose-xcover
- python-nose2
- python-notebook
- python-novaclient-os-networks
- python-novaclient-os-virtual-interfaces
- python-ntplib
- python-num2words
- python-nwdiag
- python-octaviaclient
- python-ofxparse
- python-openoffice
- python-openopt
- python-openqa_client
- python-openstack-nose-plugin
- python-os-brick
- python-oslo-cache
- python-oslo-reports
- python-oslo-versionedobjects
- python-oslo-vmware
- python-pacpy
- python-paho-mqtt
- python-pamela
- python-pandas-datareader
- python-pankoclient
- python-parallel-ssh
- python-parso
- python-partd
- python-pathspec
- python-pdfkit
- python-pdfminer
- python-pdir2
- python-pecan-notario
- python-pefile
- python-pep8-naming
- python-persist-queue
- python-pg8000
- python-pgpdump
- python-phabricator
- python-photutils
- python-pid
- python-piexif
- python-pint
- python-plaintable
- python-pluginbase
- python-plyvel
- python-podcastparser
- python-poppler-qt4
- python-port-for
- python-posix_ipc
- python-power
- python-praw
- python-profilehooks
- python-progress
- python-proliantutils
- python-prov
- python-psycogreen
- python-ptrace
- python-pudb
- python-py2neo
- python-py2pack
- python-py9p
- python-pyactivetwo
- python-pyaes
- python-pybeam
- python-pybloomfiltermmap
- python-pycdlib
- python-pydocstyle
- python-pyeclib
- python-pygatt
- python-pygments-markdown-lexer
- python-pygments-style-solarized
- python-pyinsane2
- python-pykalman
- python-pykmip
- python-pykwalify
- python-pylcdsysinfo
- python-pylons-sphinx-themes
- python-pymediainfo
- python-pymemcache
- python-pymoc
- python-pymssql
- python-pyopencl
- python-pyoptical
- python-pypng
- python-pyprocdev
- python-pypump
- python-pyqtgraph
- python-pyrad
- python-pyramid-chameleon
- python-pyriemann
- python-pyro
- python-pyrpmmd
- python-pyspf
- python-pystray
- python-pyswip
- python-pytaglib
- python-pytelegrambotapi
- python-pytest-beakerlib
- python-pytest-benchmark
- python-pytest-faulthandler
- python-pytest-testmon
- python-pytest-tornado
- python-pytest-watch
- python-pytoml
- python-pyuv
- python-pyvmomi
- python-pyvo
- python-pyxid
- python-pyxs
- python-pyzabbix
- python-pyzolib
- python-q
- python-qrencode
- python-quantities
- python-rasterio
- python-rauth
- python-rcssmin
- python-recommonmark
- python-relatorio
- python-represent
- python-requests-cache
- python-requests-ftp
- python-requests-gssapi
- python-restauth
- python-restructuredtext-lint
- python-restsh
- python-retryz
- python-rfc3987
- python-ripe-atlas-cousteau
- python-ripe-atlas-sagan
- python-rows
- python-rpdb
- python-rpyc
- python-rsdclient
- python-rstcheck
- python-rtslib
- python-rxjson
- python-ryu
- python-saharaclient
- python-sanction
- python-schema
- python-scrapy
- python-scrypt
- python-seesaw
- python-semver
- python-sendgrid
- python-sep
- python-serpy
- python-setuptools_hg
- python-shade
- python-shadowsocks
- python-shortuuid
- python-sievelib
- python-signalfd
- python-simplebayes
- python-simpleeval
- python-simpleparse
- python-simplepath
- python-simplevisor
- python-simpy
- python-slackclient
- python-smbc
- python-smbpasswd
- python-social-auth
- python-softlayer
- python-sortedcontainers
- python-speedtest-cli
- python-sphinx-argparse
- python-sphinx-autobuild
- python-sphinx-gallery
- python-sphinx-intl
- python-sphinx-theme-py3doc-enhanced
- python-sphinxcontrib-actdiag
- python-sphinxcontrib-adadomain
- python-sphinxcontrib-autoprogram
- python-sphinxcontrib-blockdiag
- python-sphinxcontrib-seqdiag
- python-sphinxcontrib-spelling
- python-sql
- python-sqlacodegen
- python-sseclient
- python-stdnum
- python-stem
- python-streamlink
- python-structlog
- python-subliminal
- python-svgwrite
- python-sysv_ipc
- python-tackerclient
- python-tambo
- python-taskflow
- python-tasklib
- python-taskw
- python-tbgrep
- python-tblib
- python-terminaltables
- python-testfixtures
- python-testify
- python-testinfra
- python-testing.postgresql
- python-texttable
- python-tgscheduler
- python-thriftpy
- python-tidy
- python-tinycss2
- python-tinydb
- python-tooz
- python-tortilla
- python-tosca-parser
- python-tpg
- python-treq
- python-trezor
- python-troveclient
- python-twiggy
- python-twilio
- python-twitter
- python-txredisapi
- python-ufo2ft
- python-uinput
- python-unipath
- python-units
- python-upoints
- python-uri-templates
- python-urllib-gssapi
- python-urlobject
- python-usbtmc
- python-validators
- python-virtkey
- python-vitrageclient
- python-vulture
- python-vxi11
- python-walkdir
- python-wand
- python-webpy
- python-whichcraft
- python-wikipedia
- python-wikitcms
- python-windtalker
- python-wordpress-xmlrpc
- python-wtf-peewee
- python-www-authenticate
- python-wxpython4
- python-xapp
- python-xcffib
- python-xhtml2pdf
- python-xml2rfc
- python-xmlrunner
- python-xmlsec
- python-xtermcolor
- python-xvfbwrapper
- python-yamlordereddictloader
- python-yapsy
- python-yara
- python-yattag
- python-yourls
- python-zanata2fedmsg
- python-zaqarclient
- python-zc-buildout
- python-zict
- python-zipstream
- python-zope-contenttype
- python-zope-datetime
- python-zope-dottedname
- python-zope-filerepresentation
- python-zope-i18n
- python-zope-processlifetime
- python-zope-proxy
- python-zope-sequencesort
- python-zope-structuredtext
- qhexedit2
- rdkit
- rhn-client-tools
- rpmdeplint
- satyr
- shogun
- spyder
- systemd-coredump-python
- systemtap
- tbb
- tlsh
- transtats-cli
- tweepy
- vigra
- vrpn
- weasyprint
- woffTools
- xrootd
- z3

</details>

In scope of #382

### CODE REVIEW

**Comment by encukou** [comment]
This is looking good, thanks!

One thing I'd consider is that the whole package would get legacy leaf status only if *all* its py2 packages are leaves. In simple cases it probably won't matter, and but we'll make packagers' lives easier if we only suggest removing all of py2 in go.

Nitpick: Existing status names `py2-only` (and `in-progress`) use hyphens, so I'd go for `legacy-leaf` rather than `legacy_leaf`.

**Comment by irushchyshyn** [comment]
Thanks for taking a look. I agree with both statements, will change.

**Comment by encukou** [comment]
I've pushed a rewording commit to rename the (now misleading) "Released" state, make the message more friendly, and re-style the Leaf RPM icon. Do these changes look good to you?

**Comment by irushchyshyn** [comment]
@encukou thanks for the update and review! Your changes look great (sorry for using radioactive yellow for autumn leaves).

**Comment by encukou** [comment]
Oh, no need to be sorry! The connection to autumn only hit me when I saw the yellow, actually :)

**Pull request merged**
