### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
## Part 1

**idle** → **missing** (1)
- ompl ([BR fix](https://src.fedoraproject.org/rpms/ompl/c/b236403ca602cb5b5fbdf5c51b28a9ed3905daf5?branch=master))

**idle** → **py3-only** (3) ♥
- bookworm (recently got through package review with py2 dependency; now fixed)
- libccd (BR fix)
- mingw-qt5-qtwebkit (BR fix)

**legacy-leaf** → **py3-only** (1)
- python-docutils (siddharthvipul1 0→1 :1st_place_medal:)

**missing** → **py3-only** (20)
- androwarn
- avocado-vt
- libaccounts-glib
- mkdocs-alabaster
- mkdocs-bootstrap
- mkdocs-cinder
- mkdocs-material
- mm-common
- pax-utils
- python-apypie
- python-click-help-colors
- python-colcon-ros-bundle
- python-colorzero
- python-cppy
- python-cx-oracle
- python-cxxfilt
- python-freeipa
- python-pytenable
- python-siphash
- python-steps

**released** → **legacy-leaf** (1)
- python-pycryptodomex (mistake in python-dns)

**released** → **py3-only** (1)
- python-dns ([mistake](https://bugzilla.redhat.com/show_bug.cgi?id=1824946))

## Part 2

**idle** → **py3-only** (1) ♥
- pspp (BR fix) (peter 3→4)

**missing** → **py3-only** (2)
- apostrophe
- mint-themes

**py3-only** → **missing** (4)
- picom
- python-flask-cache
- python-nose-cov
- python-nose-xcover

**py3-only** → **released** (1)
- python-dns (mistake fixed)

### CODE REVIEW

**Comment by hroncok** [comment]
> python-pycryptodomex (mistake in python-dns)

This will be now only recommended. As such we should talk to mailman and trac spam filter people to check whether we can drop it, or whether they need to manually require it.

**Comment by hroncok** [comment]
I'd be more comfortable merging this after python2-dns lands in the compose. Or to merge this as is, but do the next update as soon as that happens.

**Comment by encukou** [comment]
OK, I'll hold off.

**Comment by hroncok** [comment]
```
$ repoquery --repo=rawhide{,-source} python2-dns
python2-dns-0:1.16.0-10.fc33.noarch
```

**Comment by encukou** [comment]
Thanks. I appended another update to this PR.

**Comment by hroncok** [comment]
pspp badge?

**Comment by encukou** [comment]
Sorry for the mess here, I to check for open PRs before I pushed to my update branch.

6834cdd is merged; it has the pspp badge entry.

**Pull request closed without merging**
