### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by irushchyshyn**
**idle -> legacy-leaf (2)**
- edk2, not fully ported, note added
- python-pyghmi, [updated](https://src.fedoraproject.org/rpms/python-pyghmi/c/585933590f464102a20e1e570bf8cf61758f2683?branch=master) by Ilya Etingof (etingof), Parselmouth I 🥇 

**idle -> mispackaged (2)**
- python-zbase32, [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1622381)
- pyutil, [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1622380)

**idle -> missing (2)**
- deepin-menu, [dependency dropped](https://src.fedoraproject.org/rpms/deepin-menu/c/3086cc4e7807c3fddfac5df7e1c156ced7d117d7?branch=master)
- nodejs, [dependency dropped](https://src.fedoraproject.org/rpms/nodejs/c/ec1e55a94c6618de9667bab22146e481798ba958?branch=master)

**idle -> released (2)**
- munin, [updated](https://src.fedoraproject.org/rpms/munin/c/5c2cefb8d76c31bad04db2d7fd6a86d4c25542e7?branch=master) by Kim B. Heino (kimheino), Parselmouth I 🥇 
- obs-build, [updated](https://src.fedoraproject.org/rpms/obs-build/c/769e33900bc380262d56351f517ec1b741fc8f6b?branch=master) by Neal Gompa (ngompa), Parselmouth I 🥇 

**legacy-leaf -> missing (10)**
- python-djvulibre, [retired](https://src.fedoraproject.org/rpms/python-djvulibre/c/4597ffd84205a5a1c7ee8a4286542af368080322?branch=master)
- python-flask-restless, [retired](https://src.fedoraproject.org/rpms/python-flask-restless/c/4da9acc443b64a6bd6ea1bb41c366d1640b9372c?branch=master)
- python-lmiwbem, [retired](https://src.fedoraproject.org/rpms/python-lmiwbem/c/d957ad4ee624a755c18cc4ed5a6b21d3d2147bb2?branch=master)
- python-ludolph-zabbix, [retired](https://src.fedoraproject.org/rpms/python-ludolph-zabbix/c/79276332869f73bac031481be92d75623d690e59?branch=master)
- python-svgwrite, [retired](https://src.fedoraproject.org/rpms/python-svgwrite/c/7f0ff9e9ec788e1812fe8d99aa6df4aaebb2c46c?branch=master)
- python-sync2jira, [retired](https://src.fedoraproject.org/rpms/python-sync2jira/c/2aba71984a7d82068691705affad263c9cf2a949?branch=master)
- python-testfixtures, [retired](https://src.fedoraproject.org/rpms/python-testfixtures/c/b727ff60fb487144955622815e5f7f9b37cc3004?branch=master)
- python-tlslite, [retired](https://src.fedoraproject.org/rpms/python-tlslite/c/95bb7e7ae74f16dcdab3615ddb5027e7b5251564?branch=master)
- python-ufo2ft, [retired](https://src.fedoraproject.org/rpms/python-ufo2ft/c/f1468ac85271ca3586bb7940c66e237b16104014?branch=master)
- tweepy, [retired](https://src.fedoraproject.org/rpms/tweepy/c/3ed7fafba1a67d812f34d5738723139ea9057642?branch=master)

**legacy-leaf -> released (10)**
- git
- openms
- python-CacheControl
- python-docx
- python-humanize
- python-orderedmultidict
- python-oslo-cache
- python-pydicom
- python-pytools
- python-transforms3d

**mispackaged -> missing (1)**
- zeroinstall-injector, [retired](https://src.fedoraproject.org/rpms/zeroinstall-injector/c/43b4972eb3e5bbdce4a8ca2894ad959fc5b402a0?branch=master)

**mispackaged -> released (1)**
- python-oslo-db, [updated](https://src.fedoraproject.org/rpms/python-oslo-db/c/02140eee29b15dad2277b6c969497f7640bbf4b7?branch=master) by Haïkel Guémar (hguemar)

**missing -> legacy-leaf (2)**
- nest
- python-inotify_simple

**missing -> released (14)**
- OpenMolcas
- ocrmypdf
- python-asyncssh
- python-coverage_pth
- python-mplcursors
- python-pikepdf
- python-pyshtools
- python-pytest-expect
- python-pytest-helpers-namespace
- python-ruffus
- python-u-msgpack-python
- python-xmp-toolkit
- rlwrap
- textern

**released -> legacy-leaf (8)**
- autowrap
- python-booleanoperations
- python-compreffor
- python-cu2qu
- python-jira
- python-mimerender
- python-nose_fixes
- python-zabbix-api-erigones

**released -> missing (3)**
- python-ludolph, [retired](https://src.fedoraproject.org/rpms/python-ludolph/c/ba0397f0573df4a3f742d138b162eec9b39323b8?branch=master)
- python-sleekxmpp, [retired](https://src.fedoraproject.org/rpms/python-sleekxmpp/c/823e7275927c299e3c56ad5ea93521f663a089a7?branch=master)
- rtv, [retired](https://src.fedoraproject.org/rpms/rtv/c/bfd4ada5668685e0ea57d7c23c4989a9a52428df?branch=master)

**_Naming status changes_**
**misnamed -> named correctly (4)**
- python-magnumclient
- python-oslo-policy
- python-oslo-reports
- python-oslo-serialization

**requires blocked -> requires misnamed (18)**
- python-barbicanclient
- python-congressclient
- python-heatclient
- python-manilaclient
- python-muranoclient
- python-novaclient
- python-os-brick
- python-pankoclient
- python-pycadf
- python-saharaclient
- python-taskflow
- python-tooz
- python-ironicclient
- python-cursive
- python-glance-store
- python-aodhclient
- python-ceilometerclient
- python-networking-bigswitch

**requires blocked -> requires ok (5)**
- python-neutronclient
- python-oslo-log
- python-oslo-versionedobjects
- python-keystoneclient
- python-keystonemiddleware

**requires misnamed -> requires ok (6)**
- python-oslo-vmware
- mariadb
- python-zaqarclient
- moose
- python-oslo-db
- python-oslo-middleware

**requires ok -> requires misnamed (2)**
- python-cinderclient
- python-oslo-i18n

### CODE REVIEW

**Comment by hroncok** [comment]
etingof, kimheino and ngompa will get the Parselmouth I badge?

**Comment by irushchyshyn** [comment]
Uu, right, the badges :)

**Comment by encukou** [comment]
Thank you! Badges awarded.

Interestingly, the OpenStack projects are switching to `python2-` dependencies! \o/
I've looked at a few of the `python-*client` packages in "requires blocked -> requires misnamed", and they have very nice updates from Haïkel from a few days ago.

**Comment by hroncok** [comment]
But the switched python2-sphinx to python-sphinx (by Haïkel's update). I'd assume it's the "we don't care what Python version sphinx is" argument.,

**Pull request merged**
