### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
## Update Fedora data

**idle** → **mispackaged** (1)
- fedora-easy-karma (Will go back to idle in next update. [Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1650648) blocked [PYTHON3](https://bugzilla.redhat.com/show_bug.cgi?id=PYTHON3) directly, should only block [PYTHON3-UPSTREAM](https://bugzilla.redhat.com/show_bug.cgi?id=1322027) until upstream is ported.)

**idle** → **missing** (7)
- pulp
- pulp-docker
- pulp-ostree
- pulp-puppet
- pulp-python
- pulp-rpm
- python-crane

**idle** → **released** (4)
- appliance-tools (ngompa 3→4)
- bodhi (recorded already)
- octave-miscellaneous (orion 14→15 !)
- python-modestmaps (cottsay 0→1 :1st_place_medal:)

**legacy-leaf** → **released** (7)
- conu
- libtaskotron
- python-envisage
- python-gmpy2
- python-metakernel
- python-nb2plots
- python-subunit2sql

**mispackaged** → **missing** (1)
- ecryptfs-utils

**missing** → **released** (5)
- asv
- linux-system-roles
- python-brian2
- python-nineml
- python-pyemd

**released** → **legacy-leaf** (17)
- createrepo_c
- python-AppTools
- python-cornice-sphinx
- python-feedgen
- python-mongoengine
- python-okaara
- python-oslo-db
- python-pyramid-fas-openid
- python-rpmfluff
- python-scripttester
- python-simplemediawiki
- python-sqlalchemy_schemadisplay
- python-texext
- python-twine
- python-xunitparser
- subscription-manager
- testcloud

## Naming status changes

**misnamed** → **missing** (1)
- pulp-python

**missing** → **requires misnamed** (1)
- colobot ([PR](https://src.fedoraproject.org/rpms/colobot/pull-request/1))

**named correctly** → **missing** (7)
- ecryptfs-utils
- pulp
- pulp-docker
- pulp-ostree
- pulp-puppet
- pulp-rpm
- python-crane

**requires blocked** → **requires ok** (1)
- pycairo

**requires misnamed** → **missing** (3)
- pulp
- python-crane
- pulp-rpm

**requires misnamed** → **requires ok** (2)
- python-subunit2sql
- python-metakernel

### CODE REVIEW

**Comment by hroncok** [comment]
> Bug blocked PYTHON3 directly, should only block PYTHON3-UPSTREAM until upstream is ported.

Oh, sorry.

> octave-miscellaneous (orion 14→15 !)

Isn't that a badge?

> released → legacy-leaf (17)

All PY2REMOVAL bugs filled.

**Comment by hroncok** [comment]
> Bug blocked PYTHON3 directly, should only block PYTHON3-UPSTREAM until upstream is ported.

Oh, sorry.

> octave-miscellaneous (orion 14→15 !)

Isn't that a badge?

> released → legacy-leaf (17)

All PY2REMOVAL bugs filled.

**Comment by encukou** [comment]
> > octave-miscellaneous (orion 14→15 !)
> 
> Isn't that a badge?

No, badges are at 1, 5 and 10.

**Comment by hroncok** [comment]
oh, I thought 15.

**Pull request merged**
