### PR TITLE
Update Fedora data

### PR DESCRIPTION
**Pull request by encukou**
This includes #584.

Looks like we're down to basic commodoties like `rubber` and `salt`!

---

**idle** → **missing** (37)
- ailurus
- bleachbit
- cherrytree
- cmpi-bindings
- did
- dpm-contrib-admintools
- earcandy
- fedwatch
- gilmsg
- gjots2
- ipsilon
- jabber-roster
- lcgdm
- ldtp
- libglade2
- mote
- packagedb-cli
- pology
- puddletag
- pybliographer
- pychecker
- python-fedmsg-meta-debian
- python-fmn-consumer
- python-ipaddress
- python-moksha-wsgi
- python-mox
- python-pwntools
- python-robosignatory
- python-salttesting
- python-summershum
- python-xunitmerge
- python2  \o/
- shcov
- subversion
- surl
- trac-fedmsg-plugin
- vhybridize

**idle** → **py3-only** (7) ♥
- crudini (pbrady 0→1 :1st_place_medal:)
- fedora-gather-easyfix (pingou 2→3)
- nwchem (marcindulak 1→2)
- python-tilestache (cottsay 1→2)
- rabbitvcs (pwalter 0→1 :1st_place_medal:)
- rubber (sergiopr 1→2)
- salt (dmurphy18 0→1 :1st_place_medal:)

**legacy-leaf** → **missing** (1)
- pystache

**legacy-leaf** → **py3-only** (17)
- odfpy
- python-anykeystore
- python-blinker
- python-daemon
- python-jwt
- python-repoze-lru
- python-scour
- python-transaction
- python-translationstring
- python-txws
- python-txzmq
- python-venusian
- python-vulture
- python-zope-component
- python-zope-configuration
- python-zope-deprecation
- rrdtool

**missing** → **idle** (5)
- gnome-python2
- gnome-python2-desktop
- python2-pip
- python2-setuptools
- python27  /o\

**missing** → **py3-only** (7)
- inkscape
- is-it-in-rhel
- python-boolean.py
- python-ifcfg
- python-ruamel-yaml-clib
- python-timeout-decorator
- python-tw2-core

**released** → **legacy-leaf** (23)
- lasso
- pyatspi
- pysvn
- python-ROPGadget
- python-audioread
- python-bleach
- python-bugzilla
- python-chameleon
- python-dpath
- python-enchant
- python-kajiki
- python-libcloud
- python-modestmaps
- python-moksha-common
- python-msgpack
- python-pika
- python-redis
- python-sieve
- python-systemd
- python-vcrpy
- python-zope-i18nmessageid
- python-zope-schema
- unicorn

**released** → **py3-only** (10)
- fedmsg
- pystatgrab
- python-acoustid
- python-fedmsg-meta-fedora-infrastructure
- python-jwcrypto
- python-pip
- python-setuptools
- python-tw2-forms
- python-tw2-jqplugins-ui
- python-tw2-jquery

Naming status changes
---------------------

**named correctly** → **missing** (38)
- ailurus
- bleachbit
- cherrytree
- cmpi-bindings
- did
- dpm-contrib-admintools
- earcandy
- fedwatch
- gilmsg
- gjots2
- ipsilon
- jabber-roster
- lcgdm
- ldtp
- libglade2
- mote
- packagedb-cli
- pology
- puddletag
- pybliographer
- pychecker
- pystache
- python-fedmsg-meta-debian
- python-fmn-consumer
- python-ipaddress
- python-moksha-wsgi
- python-mox
- python-pwntools
- python-robosignatory
- python-salttesting
- python-summershum
- python-xunitmerge
- python2
- shcov
- subversion
- surl
- trac-fedmsg-plugin
- vhybridize

**requires misnamed** → **missing** (3)
- cherrytree
- lcgdm
- puddletag

**requires misnamed** → **requires ok** (1)
- salt

### CODE REVIEW

**Comment by hroncok** [comment]
I'm working on a fix.

**Comment by hroncok** [comment]
I've pushed 2 extra commits.

**Comment by encukou** [comment]
Actually, python27's dependencies are quite tame, so the `usual_suspects` speedup isn't needed.
(I thought this would make a workaround unnecessary, but it looks like the algorithm isn't quite right, and I don't think it's worth debugging, so I adjusted a comment and left it in.)

**Comment by hroncok** [comment]
Thanks, let's ship it!

**Pull request merged**
